### ISSUE TITLE
Commands fails when input data is an array

### ISSUE THREAD

**Issue by hydrargyrum** [mattrobenolt/jinja2-cli#112]
```
% echo > basic.j2
% echo '[{}]' > basic.json
% jinja2 --format=json basic.j2 basic.json
Traceback (most recent call last):
  File "/xxx/.local/bin/jinja2", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/xxx/.local/lib/python3.11/site-packages/jinja2cli/cli.py", line 449, in main
    sys.exit(cli(opts, args))
             ^^^^^^^^^^^^^^^
  File "/xxx/.local/lib/python3.11/site-packages/jinja2cli/cli.py", line 327, in cli
    data.update(parse_kv_string(opts.D or []))
    ^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'update'
```

**Comment by mattrobenolt** [comment]
Yeah, I guess that's true. Data is intended to be key/value pairs. The same could be said for any other type. What are you trying to accomplish?

**Comment by mattrobenolt** [comment]
You should be able to do that pretty easily on your own with some pipe like `jq` before passing it in. From a templating POV it makes no sense to not handle a dict for input.

**Comment by hydrargyrum** [comment]
Ok that's what I did, closing from my side. But that could have been an improvement to support such JSON files as they're not uncommon.
