### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Jenselme** [mattrobenolt/jinja2-cli#16]
Hi,

Since jinja2-cli got some new functionalities since the last release, can we have a new one? It would also be easier for me to use it on my projects.

**Comment by mattrobenolt** [comment]
Yeah, totally. I was working on something else to add to this, but I can hold off. I'll get a release cut today. :)

**Comment by mattrobenolt** [comment]
0.5.0 has been pushed to pypi: https://pypi.python.org/pypi/jinja2-cli/0.5.0

**Comment by Jenselme** [comment]
Thanks!
