### ISSUE TITLE
Warn about missing attributes

### ISSUE THREAD

**Issue by tatref** [mattrobenolt/jinja2-cli#19]
Hi,

When rendering a template with missing attributes, I get no warning or return code indicating the issue.

j2 warns the user with `jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'some_mising_attribute'`

I'm using the following versions:
```
j2 --version
j2cli 0.3.1-0, Jinja2 2.8
```

```
jinja2 --version
jinja2-cli v0.5.0
 - Jinja2 v2.8
```

I think the issue is in the call to the `render`method, but I could not spot any difference with the way j2 calls the render.

Tell me if you need help to investigate this.

Thanks

**Comment by mattrobenolt** [comment]
Yeah, the default behavior of jinja2 is to ignore undefined objects in templates. If I added this, I think I'd prefer it to be a command line argument.

Not entirely sure about `j2`, but to make this work here, it's a matter of passing: `undefined=jinja2.StrictUndefined` to the `Environment`.

Would you be open for a CLI argument `--strict`? That makes sense to me.

**Comment by tatref** [comment]
Thanks for the quick fix!
