### ISSUE TITLE
Update version available in pip

### ISSUE THREAD

**Issue by joaocc** [mattrobenolt/jinja2-cli#23]
Hi,
I noticed that doing `pip install j2cli[yaml]` and `pip3 install j2cli[yaml]` installs v0.3.1.
How can we get it updated to 0.5+?
Thx

**Comment by mattrobenolt** [comment]
You're installing the wrong project. This is `jinja2-cli`.

https://pypi.python.org/pypi/jinja2-cli

**Comment by mattrobenolt** [comment]
`j2cli` is here: https://pypi.python.org/pypi/j2cli

**Comment by joaocc** [comment]
Thanks!
