### ISSUE TITLE
Jinja2 template from STDIN?

### ISSUE THREAD

**Issue by ye** [mattrobenolt/jinja2-cli#24]
I've searched through the code but it doesn't seem to allow output to STDOUT independent of input. Can we add this feature? The use case would be to pass param via `-D` but render to jinja2 template of config without having to generate a file.

**Comment by mattrobenolt** [comment]
I'm not sure what you mean. It _only_ writes to stdout: https://github.com/mattrobenolt/jinja2-cli/blob/master/jinja2cli/cli.py#L234

**Comment by ye** [comment]
Hi Matt again! :)

Pardon me if I wasn't being clear. I am just having some hard time understanding the syntax of the parameters. In particular, there is no way to take j2 template from STDIN and/or using the `-D` only as the input data. 

Here are the logs of me fiddling around without luck to get it to work. Python 2.7.11, Jinja 2.8, jinja-cli 0.5.0. Any pointers would be helpful.

```bash
$ cat test.j2
apiVersion: batch/v1
kind: Job
metadata:
  name: a_job
spec:
  template:
    metadata:
      name: foo
    spec:
      containers:
        - name: foo
          image: https://registry.hub.docker.com/_/testco/foo:{{ tag }}
          command: ['/bin/bash', 'run.sh', {{ tag|safe }}]
$ cat test.j2 | jinja2 -D tag=9562f6b3770a -
^D
Traceback (most recent call last):
  File "/usr/local/bin/jinja2", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/jinja2cli/cli.py", line 287, in main
    cli(opts, args)
  File "/usr/local/lib/python2.7/site-packages/jinja2cli/cli.py", line 205, in cli
    raise formats[format][2](u'%s ...' % data[:60])
jinja2cli.cli.MalformedYAML: apiVersion: batch/v1
kind: Job
metadata:
  name: a_job
spec: ...
$ jinja2 test.j2 -D tag=9562f6b3770a --format=yaml
^D
Traceback (most recent call last):
  File "/usr/local/bin/jinja2", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/jinja2cli/cli.py", line 287, in main
    cli(opts, args)
  File "/usr/local/lib/python2.7/site-packages/jinja2cli/cli.py", line 216, in cli
    data.update(parse_kv_string(opts.D or []))
AttributeError: 'NoneType' object has no attribute 'update'
```

PS: will update the issue title.

**Comment by mattrobenolt** [comment]
Oh, you're right. You can't load a template from stdin. This is fundamentally because stdin is already reserved for actual variable context.

I think it'd be confusing to overload what stdin is used for. I'm just thinking of the situation where someone is wanting to do both variables and template over stdin, which, obviously won't work.

**Comment by mattrobenolt** [comment]
I guess I'd be ok with explicitly allowing `-` as the input template target.

And if `-` is passed, variables can't be accepted over stdin as well.

**Comment by ye** [comment]
Ok, I got it now. I forgot the jinja2 template context is required as well :(

In a of the [command line usages of jinja2 templates](https://cloud.google.com/deployment-manager/configuration/adding-templates), I would think a quick & dirty taking the j2 template from STDIN, with a bunch of `-D` key-value pairs and then output something to the STDOUT. But it's a shame that context occupies the STDIN. Jinja2 templates will have to be specified as a file. Wouldn't it actually be better if we swap the places between context and jinja2 template? That way, STDIN for jinja2 template, no argument for context means it's empty or else specify it as a file. STDOUT for rendered content unchanged. In my use case described above, `jinja2` will perform as a true unix pipe utility :)

> I think it'd be confusing to overload what stdin is used for. I'm just thinking of the situation where someone is wanting to do both variables and template over stdin, which, obviously won't work.

Apparently that someone was me! :)

**Comment by dd-ssc** [comment]
I'm aware this is an ancient issue and I've read the [comment on design decisions](https://github.com/mattrobenolt/jinja2-cli/issues/90#issuecomment-642356803), but I'm still wondering:
How do you then use `jinja` with no files involved at all and only passing template variables using `-D` ?

**Comment by mattrobenolt** [comment]
I've never personally needed that, I've always had the templates on disk.

If we want to support this, we'd need some new flag to toggle what STDIN means. Since we can have two STDINs.

But I'm not sure of any precedent of tools that would behave this way.
