### ISSUE TITLE
Add support for environment variables

### ISSUE THREAD

**Issue by zoidbergwill** [mattrobenolt/jinja2-cli#25]
The main reason I use [j2cli](https://github.com/kolypto/j2cli) at the moment is for it's support of environment variables, but it doesn't support Python 3 and no one seems to be maintaining it.

Would a patch to add environment support be considered?

**Comment by mattrobenolt** [comment]
This does support environment variables already. See: https://github.com/mattrobenolt/jinja2-cli/blob/master/jinja2cli/cli.py#L173-L174

Should be accessible as `{{ environ('SOMETHING') }}`

**Comment by zoobab** [comment]
Well, I do not like this, as I have to modify all my .j2 templates to force sourcing those variables, instead of the unmaintained j2 tool was supporting env vars as source.

Could you consider adding that support as well?

**Comment by mattrobenolt** [comment]
I don't understand what you're asking. Can you give me an example?
