### ISSUE TITLE
can't use enviroment variable

### ISSUE THREAD

**Issue by wifasoi** [mattrobenolt/jinja2-cli#31]
I noted i can't use the enviroment variable in my template [commit: 4b6c048]. I made some testing with this template:
[export TEST=succes]
`{% if environ.TEST is defined %}TEST={{ environ.TEST }}{% endif %}`

I pin-poin the issue at this [line](https://github.com/mattrobenolt/jinja2-cli/blob/master/jinja2cli/cli.py#L181):
`env.globals['environ'] = os.environ.get`
I'm not an expert with jinja2, but i think you need to pass a dictionary (I noticed an iterable is fine) and not a fuction.
I fixed by changing the line with:
`env.globals['environ'] = dict(os.environ)`
or (becouse os.environ is iterable)
`env.globals['environ'] = os.environ`

I think the functionality need to be documented in the README.

**Comment by mattrobenolt** [comment]
The intended usage is:

```
{{ environ('FOO') }}
{{ environ('FOO', 'somedefault') }}
```

So the behavior I have now is correct. This is the same as doing `os.environ.get('foo', bar')`

**Comment by mattrobenolt** [comment]
And yeah, I didn't realize this wasn't documented. Should definitely add that.

**Comment by wifasoi** [comment]
(sorry if i bother you.. but just for the records)
This is down to choice in the program behavior, but with your approach you can't use the "is define" statement. A possible work-around is to  do the followings:
`{% if environ('FOO', False) %}`

**Comment by mattrobenolt** [comment]
@wifasoi I'd do this:

```python
{% if environ('FOO') is none %}
it doesn't exist
{% else %}
{{ environ('FOO') %}
{% elseif %}
```

So instead of `is defined` you can just as easily use `is none`.
