### ISSUE TITLE
keep_trailing_newline not configurable?

### ISSUE THREAD

**Issue by jefftp** [mattrobenolt/jinja2-cli#40]
keep_trailing_newline is True by default with jinja2-cli, which is not the prescribed default configuration of Jinja2 (http://jinja.pocoo.org/docs/2.9/templates/#whitespace-control). There doesn't appear to be a way to alter this behavior short of modifying the code?

The issue at hand is that this makes one particular scenario a huge challenge: conditionals with whitespace sensitive output. For example,

```
Keep the blank below this line.

{% if variable1 %}
    Variable1 is true.
{% elif variable2 %}
    Variable2 is true.
{% endif %}

Keep the blank above this line.
```

Without any "-" for whitespace control, you get added newlines. If you add a trailing "-" to the statement jinja will eat all the whitespace, newline and spaces. If you add a leading "-" to the statement then jinja will eat all the leading whitespace and newlines. All options ruin whitespace formatting and you're forced to putting the Jinja2 templates inline--making reading the source material more challenging.

**Comment by jefftp** [comment]
Even with keep_trailing_newline set to false I can't get Jinja to get rid of a trailing newline.

**Comment by mattrobenolt** [comment]
Yeah, I think this is unrelated. This setting is literally related to a single newline character at the end of the file. Similar to how a lot of text editors will add a newline at the end. I'm choosing to keep whatever is input file already has.

**Comment by jefftp** [comment]
Withdrawing issue as it has nothing to do with keep_trailing_newline.
