### ISSUE TITLE
Loading context from STDIN returns error on Windows

### ISSUE THREAD

**Issue by mike-rsi** [mattrobenolt/jinja2-cli#51]
Hi,

I use this tool often in a Windows environment (Git Bash to be specific) and would like to start using the feature where you can load the context/data on STDIN.  This seems to work fine on Linux, but on Windows [8.1 Pro] returns this error:

(Note: this is using the files from the `sample/` directory in the project's repo)

```bash
#
# Passing the template and context as arguments on the command line works:
#
$ jinja2 sample.jinja2 sample.json
<html>

<ul>
    <li>foo</li>
    <li>bar</li>
    <li>baz</li>
    </ul>

</html>
#
# Trying to load the context from STDIN returns an error:
#
$ cat sample.json | jinja2 sample.jinja2
Traceback (most recent call last):
  File "c:\python27\Lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\Mike\.virtualenvs\myproject\Scripts\jinja2.exe\__main__.py", line 9, in <module>
  File "c:\users\mike\.virtualenvs\myproject\lib\site-packages\jinja2cli\cli.py", line 335, in main
    sys.exit(cli(opts, args))
  File "c:\users\mike\.virtualenvs\myproject\lib\site-packages\jinja2cli\cli.py", line 195, in cli
    if is_fd_alive(sys.stdin):
  File "c:\users\mike\.virtualenvs\myproject\lib\site-packages\jinja2cli\cli.py", line 189, in is_fd_alive
    return bool(select.select([fd], [], [], 0)[0])
select.error: (10038, 'An operation was attempted on something that is not a socket')
```

**Comment by mattrobenolt** [comment]
This would definitely be coming from here:

https://github.com/mattrobenolt/jinja2-cli/blob/master/jinja2cli/cli.py#L214-L218

What is `os.name` for you? I don't have access to any Windows machine to even test this, so any help here would be great.

**Comment by mike-rsi** [comment]
It looks like it's returning what you're expecting:
```shell
$ python
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.name
'nt'
>>>
```

Although looking at the source of the pip installed package on my local machine...

`site-packages/jinja2cli/cli.py` (L#187-189):
```
def is_fd_alive(fd):
    import select
    return bool(select.select([fd], [], [], 0)[0])
```

It doesn't look like my version has the patch you referred to that checks for `os.name`.

```
$ jinja2 --version
jinja2-cli v0.6.0
 - Jinja2 v2.9.6
```

Perhaps I just have to wait for the latest changes to make it into PyPI?

**Comment by mattrobenolt** [comment]
Ah, you're right. This came from here: https://github.com/mattrobenolt/jinja2-cli/pull/45

I'll get a new release tagged.

**Comment by mattrobenolt** [comment]
Let me know if this isn't fixed in latest release.
