### ISSUE TITLE
[Feature Request] Specify output file

### ISSUE THREAD

**Issue by hubertgrzeskowiak** [mattrobenolt/jinja2-cli#56]
Heya!
Since redirecting the output of a command relies on the used shell, it would be quite helpful to have a parameter that tells the program where to write the rendered template to.

**Comment by zoobab** [comment]
+1

**Comment by pawamoy** [comment]
And what would be great is to make this option support a Jinja2 string as output name, so we can use context variable in the output name :slightly_smiling_face:

**Comment by mattrobenolt** [comment]
Care to provide an example of that? Not sure when that'd be needed.

**Comment by pawamoy** [comment]
Hmm. Let say you have a tool `get-json-metadata` that parses files and outputs metadata as JSON.

```
for file in *; do
  get-json-metadata "$file" | jinja2 /my/template \
    --output '{{ metadata.file_type }}/{{ metadata.file_name }}.{{ metadata.file_version }}'
```

**Comment by hubertgrzeskowiak** [comment]
My use case is rendering templates in shells that don't support output redirection or when you can't rely on it, e.g. in Dockerfiles, packer-conf.json or Vagrantfiles.

**Comment by mattrobenolt** [comment]
I didn't make it handle it's own variable as a template yet, but added support for the flag for now.
