### ISSUE TITLE
no binary?

### ISSUE THREAD

**Issue by burtonator** [mattrobenolt/jinja2-cli#65]
what am I doing wrong here?

pip install jinja2-cli

yields no binary but your instructions say I can just run it as directly.  The module only installs .py and .pyc files...

**Comment by mattrobenolt** [comment]
It should install something onto `$PATH`, this is just normal Python setuptools behavior that has worked and existed for years.

When you run `pip install jinja2-cli`, do you not have `jinja2` now available on `$PATH` somewhere?
