### ISSUE TITLE
An option to ignore/bypass unknown variables

### ISSUE THREAD

**Issue by 3fr61n** [mattrobenolt/jinja2-cli#67]
Hi

Nice project BTW...

I suggest to add an option in the command line to ignore/bypass when there is a undefined variable on the template and do nothing with it, (by default the variable is replaced with null/empty)

I think this will be helpful when you have multiple variable inputs for the same template, so I can execute things like.

jinja2 --ignore_unknown my_template.j2 input1.yaml | jinja2 --ignore_unknown my_template.j2 input2.yaml | jinja2 my_template.j2 input3.yaml

Regards

**Comment by pawamoy** [comment]
I think you should instead use the template language to do what you want. You can very well check if the variable is undefined in the template, and do nothing, or use a default value.

- http://jinja.pocoo.org/docs/2.10/templates/#defined
- http://jinja.pocoo.org/docs/2.10/templates/#default

**Comment by 3fr61n** [comment]
ok... I'll use defined function and raw (for skipping variable replacements)

thanks
