### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by pawamoy** [mattrobenolt/jinja2-cli#73]
Hello :slightly_smiling_face: ! Do you plan to make a new release soon?

Currently I'm stuck because I need https://github.com/mattrobenolt/jinja2-cli/issues/72, and installing from git, master branch in GitLab CI gives me this: https://github.com/sdispater/poetry/issues/853.

**Comment by mattrobenolt** [comment]
I can work on tagging a new release. What's the context of that error though? It's just a bug in Poetry? Or a bug in jinja2-cli?

**Comment by pawamoy** [comment]
I'm pretty sure it's a Poetry bug, and jinja2-cli is not responsible at all :wink:

**Comment by tigerfoot** [comment]
Also we the release of python-3.7 the older 0.6.0 release new almost all changes in master to work.
Travis should also contain 3.7

**Comment by pawamoy** [comment]
Bump :upside_down_face: !

**Comment by pawamoy** [comment]
At the end it was my mistake :tired_face: I was using `git@github.com:` instead of `https://github.com/` in `pyproject.toml` to specify the dependency. It was working on my local development machine but not in CI (i.e. in Docker container).

A new release would still be appreciated, but it is not urgent for me anymore!

**Comment by coldfix** [comment]
Hey, would you release a new version?

I found that #51 is blocking this package to be used on windows at all.

> I can work on tagging a new release.

shouldn't take more than couple of minutes right?

**Comment by KundK** [comment]
+1 for a new release. 
In v0.6.0 INI parsing isn't working on Python 3.

**Comment by mattrobenolt** [comment]
@KundK does it work on master? iirc I haven't touched anything really with ini parsing since I don't use it myself.

**Comment by KundK** [comment]
The v0.6.0 was throwing an error on Python 3, the master one at least fixed that. But it wasn't working as I expected so switched to ENV. Which isn't in v0.6.0 at all.

**Comment by mattrobenolt** [comment]
I have pushed v0.7.0, so lemme know if this solves all the problems. I've been using this myself for a while from master pretty heavily lately without any issues, but I only use some of the paths.
