### ISSUE TITLE
Would you be interested in moban project?

### ISSUE THREAD

**Issue by chfw** [mattrobenolt/jinja2-cli#74]
Dear Matt:

moban dev team noticed your effort to bring jinja to command line interface. We are doing the same thing as you are doing. Would you like to check us out? https://moban.readthedocs.io/en/latest/

Thanks

**Comment by mattrobenolt** [comment]
What's the question? This works for my needs and apparently 200 others. Why not contribute back here? Was there something inherently wrong with my version? I don't mind, but I don't see value in switching to something else.

**Comment by chfw** [comment]
I admire the fact that 200+ users loves your project as we are all open source developers. And I respect your time and effort in serving your users for more than 6 years. But I look forward to what even more to come if we should join force and work together towards the same goal.

It is a good question why not contribute back to your project? I do not think it is ever intentional. We all started with a different use case under a different perspective in different time frame for a different goal. At one point, one open source veteran @jayvdb pointed me towards your repo. Please understand that I am not cleverer than a foo.

Nothing is wrong with your version. Please let me share some of moban features that match some of your open issues:

1) [allow user have custom jinja2 filters, tests, and globals](https://moban.readthedocs.io/en/latest/level-7-use-custom-jinja2-filter-test-n-global/README.html) , like [Ansible](https://github.com/moremoban/moban/blob/dev/moban/jinja2/tests/files.py) for #66, #44
2) [output to a specified file](https://moban.readthedocs.io/en/latest/level-1-jinja2-cli/README.html) for #56 
3) [works on py3.5, 3.6, 3.7, 3.8, even on pypy2](https://travis-ci.org/moremoban/moban/builds/503772034) for #53 
4) [bring environment variables inside template](https://github.com/moremoban/moban/pull/146) for #69
5) [allow user defined template dirs](https://moban.readthedocs.io/en/latest/level-5-custom-configuration/README.html) for #37 
6) [maybe makefile could be replaced by a yaml file](https://moban.readthedocs.io/en/latest/level-6-complex-configuration/README.html) for #72

I am sorry that I jumped in to your repo and say hello in this manner. My intention is to seek friendship and potential joint-force. If you checkout our documentation, you are more than welcome to point out what moban cannot do but jinja2-cli can. We have a [gitter channel](https://gitter.im/chfw_moban/Lobby) if you would like to chat with moban dev team.

**Comment by mattrobenolt** [comment]
Nah, that's fine. I'm just not sure what you're asking of me. Feel free to just steal code from here if you want. I write tools for me, so I will continue to develop this and use it.

Most of the issues you've pointed to aren't relevant and have already been dealt with.
