### ISSUE TITLE
jinja2-cli docker image

### ISSUE THREAD

**Issue by dinuta** [mattrobenolt/jinja2-cli#88]
Hi @mattrobenolt, 

Don't know if you have a docker image, but i integrated your cli into a image i created: 
https://github.com/dinuta/jinja2docker 

If you like it, please advertise it. It is used and tested in production.

**Comment by mattrobenolt** [comment]
Where? You don’t use it from what I can tell.

**Comment by dinuta** [comment]
> Where? You don’t use it from what I can tell.
Class:
https://github.com/dinuta/estuary-testrunner/blob/master/rest/api/eureka_registrator.py
Register call:
EurekaRegistrator(os.environ.get('EUREKA_SERVER')).register_app(os.environ["APP_IP_PORT"])

And the service boot is:
```
docker run \
-e EUREKA_SERVER=http://10.10.15.28:8080/eureka/v2 
-e APP_IP_PORT=10.10.15.28:8081
-p 8080:8080
dinutac/estuary-testrunner:latest
```

**Comment by mattrobenolt** [comment]
The only relation between your projects and mine is you happen to have it installed and need to override the entrypoint to get to it. This would be the most heavyweight way for me to recommend to others.

**Comment by dinuta** [comment]
ok @mattrobenolt. Will do in future releases after i re-validate with the new endpoint! Make sense!
Should happen in 1 month from now.

**Comment by dinuta** [comment]
HI @mattrobenolt ,

Please have a look:
https://github.com/dinuta/jinja2docker/pull/15

**Comment by mattrobenolt** [comment]
I honestly don’t understand what any of this is or why it has infinitely more complexity than I’d ever advocate for. I wouldn’t recommend this way of doing this.

**Comment by dinuta** [comment]
No problem man,

You know the best. You are the expert !

I already merged your cli as entrypoint. I won't bother you.

Cheers,

**Comment by mattrobenolt** [comment]
Sorry, so to be more constructive, if the goal is to have this in a container, why would you need more than:

```dockerfile
FROM python:3-alpine
RUN pip install jinja2-cli[yaml,toml,xml]
ENTRYPOINT ["jinja2"]
```

**Comment by dinuta** [comment]
https://github.com/dinuta/jinja2docker/blob/master/Dockerfile

@mattrobenolt
