### ISSUE TITLE
stdin

### ISSUE THREAD

**Issue by steverweber** [mattrobenolt/jinja2-cli#90]
stdin don't seem to work. it just shows help.
```
echo "test" | jinja2
```

**Comment by mattrobenolt** [comment]
Hi, what do you expect the stdin to be? There are two arguments if you read the `--help`. The first is the template to render, the second is the data.

data can be accepted over stdin, but the template itself is read from disk.

So you can do soemthing like:

```
echo '{"foo": "bar"}' | jinja2 something.j2 -
```

The design decision I had here was "which is more common to accept over stdin", and in all of my use cases, it's the data, not the template. And unfortunately, there aren't two stdins. In theory I can make the API handle one or the other or something, but that'd be pretty awkward.

**Comment by steverweber** [comment]
I see it from your POV.

my case. using docker compose where ENV vars are mostly used. Looking for something simple like..
```
export WOOT=123
echo 'what is {{WOOT}}' | jinja2 > out
or something like.
cat nginx_conf.jinja | jinja2 > /etc/nginx/nginx.conf
```

**Comment by steverweber** [comment]
found my error thanks!
